### GET USER BY ID
GET http://localhost:4000/products/product


###
### CREATE USER (SIGNUP) 
POST http://localhost:4000/products/add
Content-Type: application/json

{
  "productName": "Laptop",
  "price": 55000,
  "brand": "hp"

}
###Create User req
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "username":"ananya",
    "email":"ananya@gmail.com",
    "password":"123456"
}
###Req to cart
PUT  http://localhost:4000/users/user-cart/userid/6980a16c00c6b96d2234d577/product/6980a19100c6b96d2234d57a