### 
GET http://localhost:4000/products/product


###
POST http://localhost:4000/products/add
Content-Type: application/json

{
  "productName": "Laptop",
  "price": 55000,
  "brand": "hp"

}
###Create User req
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "username":"ravi",
    "email":"ravi@gmail.com",
    "password":"ravi",
    "cart":[]
}
###Req to cart
PUT  http://localhost:4000/users/user-cart/userid/69817f620eb006e4a819f38f/product/6980a19100c6b96d2234d57a
###

PUT http://localhost:4000/users/user-cart/69817f620eb006e4a819f38f/6980a19100c6b96d2234d57a

###
GET http://localhost:4000/users/users/69816e9fc888ee7012cac916
###
GET http://localhost:4000/users/compare/69817f620eb006e4a819f38f/6980a19100c6b96d2234d57a